FROM ruby:3.0.2

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install 
RUN bundle exec rails db:migrate
RUN bundle exec rails  db:fixtures:load
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
